version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/naseem6270/SeleniumFramework_Python/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  myfirstseleniumtest:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          print("Hello World")

workflows:
  my-custom-workflow:
    jobs:
      - myfirstseleniumtest