version: 2.1

orbs:
  python: circleci/python@2.0.3


jobs:
  example-job:

    
    docker:
    - image: circleci/python:3.6.1

    
    steps:
      - checkout
      - run: python --version
      - run: pip install pytest --user
      - python/install-packages:
          args: pytest --user
          pkg-manager: pip
          pypi-cache: false
      - run: 
          command:
            pytest businessObjects/test_Login.py


workflows:
    example-workflow:
      jobs:
        - example-job
